### ISSUE TITLE
crash on rn 0.74 with new arch enabled

### ISSUE THREAD

**Issue by advancedtw** [lodev09/react-native-true-sheet#27]
I've setup a basic project without navigation but once I add the following jsx I get a runtime exception in IOS
```jsx 
<TrueSheet ref={sheet} sizes={["auto", "large"]} cornerRadius={24}>
	<Button onPress={dismiss} title="Dismiss" />
</TrueSheet>```

pods are installed and the project builds fine.

**Comment by lodev09** [comment]
Yeah.. TrueSheet does not support New Arch at this time due to a limitation from RN interop layer with the bridge. It seems like this is only an issue with Swift codebase.

I'm waiting on the next RN version and see if they have fixed this on their end.

Closing this issue, please follow [this discussion](https://github.com/lodev09/react-native-true-sheet/discussions/20) moving forward.
