### ISSUE TITLE
[bug] inconsistent handling elements outside scrollview element ( mainly headers that don't scroll ). 

### ISSUE THREAD

**Issue by a-eid** [lodev09/react-native-true-sheet#49]
scrollviews seem to extends the full width of the sheet on IOS ( kinda like it's absolutely positioned ), however it's not the case on android which avoids the element. 

![Screenshot 2024-06-30 at 2 04 59 PM](https://github.com/lodev09/react-native-true-sheet/assets/19273413/4b4ad1aa-c19b-4e70-8499-1546eb3fa643)

**Comment by lodev09** [comment]
That's correct. IOS handles the height manually like a `position: absolute` style. On android, it's not handled at all since it works as is (only need the `nestedScrollEnabled` enabled).

The only consistent solution moving forward is to create a `HeaderComponent` so IOS will account for it when resizing, thus making both platform consistent.

For now, you can use `Platform.select()` and add `padding` to the scroll view.

**Comment by lodev09** [comment]
You could also `float` your header to make them consistent on both platform. I think that was the reason I did not add that `HeaderComponent` prop 😅

**Comment by a-eid** [comment]
@lodev09 Yeah that's what I'm already doing. I have a couple more inconsistencies 

1- android sheet seem to change colors on dark / light modes on IOS it does not. 
2- the footer component on IOS dismisses with the sheet in a linear manner, which is not the case on android there seem to be some sort of interpolation.

**Comment by lodev09** [comment]
I hate to admit it but the footer workflow on android is kinda hacky. I wish android has a straightforward way of handling all this like in IOS. It was a pain tbh.

If you could improve it, feel free to open a PR 🙏
