### ISSUE TITLE
Footer component render issue on Android

### ISSUE THREAD

**Issue by marcosrdz** [lodev09/react-native-true-sheet#56]
If you have state changes inside a true sheet in android, and u dismiss  It, present it, make changes again, dismiss it, present it, the footer sometimes ends up at where the grabber renders. 

The workaround? Make the footer part of the True Sheet children.

**Comment by lodev09** [comment]
Footer in android needs revisiting. The currently implementation is a bit hacky and I'm not really happy about it.

I'm going to try and use different approach when I get a chance.

**Comment by lodev09** [comment]
If you're not using the Footer in a scroll view, yes, add the footer as `children` instead.

**Comment by lodev09** [comment]
I played around on different solution but there's no really elegant ways to handle footer natively on android :/ Will keep it as is 
for now.

Regarding your issue, I assume it happens when you're making changes with hot reload? If that's the case, we'll have to live with it since there's really not much I can do.. But feel free to open up a PR if you find something that fixes this issue.

Thank you!

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/blob/modal/components/BottomModal.tsx


This is my workaround

**Comment by lodev09** [comment]
Good stuff wrapping it -- I do the same on mine. I don't use FooterComponent too :D
