### ISSUE TITLE
Dismount contents when dismissed

### ISSUE THREAD

**Issue by ljukas** [lodev09/react-native-true-sheet#85]
Currently the contents of a sheet are mounted even if the sheet is dismissed, would be nice if we could choose if we want the contents the be mounted or not when sheet is dismissed state

**Comment by lodev09** [comment]
Native handles this automatically so it shouldn't affect performance.

**Comment by ljukas** [comment]
Does this only apply for builds and not when in development mode ? Because on my simulator it seems to be huge burden.

**Comment by lodev09** [comment]
However, React will render content first during first load and may affect performance. I would suggest you render TrueSheet when the screen is "shown". If you're using RN navigation, you could use the transition lifecycle to detect when to render.

**Comment by ljukas** [comment]
Will try that, thanks

**Comment by ljukas** [comment]
Id like to raise this again. Even if we disregard the performance issues, putting any kind of logic that follows the following:

1. Mounts
2. Execute

Is kind of broken since stuff mounts before the modal is presented.

Say you have a query from ie. react-query inside the truesheet, now it will execute before the sheet is presented.

**Comment by ljukas** [comment]
Have made a temporary solution meanwhile:

```ts
import {
  forwardRef,
  useCallback,
  useImperativeHandle,
  useRef,
  useState,
} from 'react';

import { TrueSheet, TrueSheetProps } from '@lodev09/react-native-true-sheet';

export type TrueSheetModalMethods = {
  present: (index?: number) => Promise<void>;
  dismiss: () => Promise<void>;
  resize: (index: number) => Promise<void>;
};

export const TrueSheetModal = forwardRef<TrueSheetModalMethods, TrueSheetProps>(
  (props, ref) => {
    const internalRef = useRef<TrueSheet>(null);

    const { children, onDismiss, ...rest } = props;

    const [mounted, setMounted] = useState(false);

    useImperativeHandle(ref, () => ({
      present: async (index?: number) => {
        if (mounted) return;

        setMounted(true);
        await internalRef.current?.present(index);
      },
      dismiss: async () => {
        if (!mounted) return;

        await internalRef.current?.dismiss();
      },
      resize: async (index: number) => {
        if (!mounted) return;

        await internalRef.current?.resize(index);
      },
    }));

    const handleDismiss = useCallback(() => {
      onDismiss?.();

      setMounted(false);
    }, [onDismiss]);

    return (
      <TrueSheet ref={internalRef} onDismiss={handleDismiss} {...rest}>
        {mounted && children}
      </TrueSheet>
    );
  },
);
```

**Comment by lodev09** [comment]
On simple content, pre-rendering data/content is an advantage too. Also the height calculation is more accurate if you're not using dynamic content. The way native works is kinda complicated and requires the content to be rendered first so it's not straightforward to logic in the native side.

I'm going for the "generic" use case and special conditions require special code.

Thanks for the feedback though!

**Comment by itsnyx** [comment]
@lodev09 i also faced this issue 
because our app is complex and has 10 sheets in one screen when loading that screen all the bottom sheet contents are rendered even when they are not shown and all of these sheets has logic which will affect performance of that page 

we can go around of this with below code 
// Subscribe to the transitionEnd event ✅
useEffect(() => {
  const unsubscribe = navigation.addListener("transitionEnd", ({ data }) => {
    if (!data.closing) {
      setIsScreenShown(true)
    }
  })

  return unsubscribe
}, [])

but it would be great if we treat these sheet as screens so when we close a sheet we expect that sheet is cleared from memory to reduce memory usage 

any way thanks for the great lib currently Im trying to migrate from gorhom bottom sheet to this small and fast library !

**Comment by ljukas** [comment]
> [@ljukas](https://github.com/ljukas) does this work fine with android ? with Android I can't use `size=['auto']` it needs fixed size otherwise the content not displaying at all

@Ahmedhamed77 android 'auto' only works if you also add another size like this `size=['auto', 'large']`

**Comment by SumitR9910** [comment]
also facing this problem, pages with multiple bottom sheets become awfully slow since their content is being rendered before hand (even before they are mounted) react-navigation's `formSheet` is a possible fix for this but quite frankly the formSheet API animations (atleast on android) are horrible compared to react-native-true-sheet.
